In [22]:
import numpy as np
import random

In [20]:
y = np.linspace(1,20,5)
x = np.array([[5,6],[1,2]])
print(y)
print(x)


[  1.     5.75  10.5   15.25  20.  ]
[[5 6]
 [1 2]]


In [ ]:
#help(np.array)
#help(np.arange)
help(np.transpose)

In [153]:
M = np.ones(1)

y = np.ones((2,3))
           
    
    
print(y.shape)            
            
i = 0
while M[-1] != 10:
    ran = random.randint(1,10)
    M = np.append(M,ran)
    i+=1
    if i == 30:
        break
        
print(M)




(2, 3)
[  1.   3.   2.   8.   6.   8.   9.   4.  10.]


In [68]:
print(M[-6])
print(M.size)
print(np.mean(M))

1.0
6
4.66666666667


In [108]:
M = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
M = M.reshape(5,5)

print(np.size(M,1))

for i in np.arange(np.size(M,0)):
    for j in np.arange(np.size(M,1)):
        
        if M[i][j] % 5 == 0:
            print('Number is '+str(M[i][j])+':['+str(i)+','+str(j)+']')
            

print(np.arange(3,50,3,dtype='float'))

5
Number is 5:[0,4]
Number is 10:[1,4]
Number is 15:[2,4]
Number is 20:[3,4]
Number is 25:[4,4]
[  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.  33.  36.  39.  42.  45.
  48.]


In [145]:
A = np.array([[1,2],[4,5]])
B = np.array([1,2,6,1])
B = B.reshape(2,2)

print(B.ndim)
print(B.dtype)


print(B.shape)

x = np.array([10,20,30])
print(x)
x= np.transpose(x)



2
int64
(2, 2)
[10 20 30]


In [138]:
print(A*B)

[[ 1  4]
 [24  5]]


In [139]:
np.dot(A,B) # scalar 

array([[13,  4],
       [34, 13]])

In [140]:
np.cross(A,B) # cross product

array([  0, -26])

In [141]:
from numpy.linalg import inv # find the inverse
inv(A) 

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [172]:
a = np.array([2,3,4,5,6,7,8,9,45])
a= a.reshape(3,3)
print(a.shape)

#To get the position element at 1 from every row in the array
print(a[0:3,2]) #Fetch based on rows
print(a[1,0:3]) #Fetch based on columns

print(a[:,1:3]) # include only the columns

print(a[1:3,:]) # include  only the rows

(3, 3)
[ 4  7 45]
[5 6 7]
[[ 3  4]
 [ 6  7]
 [ 9 45]]
[[ 5  6  7]
 [ 8  9 45]]


In [184]:
a = np.arange(0,6).reshape(3,2)
print(a)
b = np.arange(10,16).reshape(3,2)
stack_arr_v = np.vstack((a,b))

print(stack_arr_v)

stack_arr_h = np.hstack((a,b))

print(stack_arr_h)

[[0 1]
 [2 3]
 [4 5]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  1 10 11]
 [ 2  3 12 13]
 [ 4  5 14 15]]


In [193]:
a = np.arange(30).reshape(2,15)
splt = np.hsplit(a,3) # Two way split horizontal
spltv = np.vsplit(a,2) # Two way split vertical
print(splt[0])
print(spltv[0])


[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
